[package]
name = "static_recompiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced-x86 = "1.21.0"
im = "15.1.0"
intervaltree = "0.2.7"
itertools = "0.12.1"
object = "0.33.0"
